// Vocabulary data for FrenchMe app
const VOCAB = [
  { fr: "bonjour", en: "hello" },
  { fr: "au revoir", en: "goodbye" },
  { fr: "merci", en: "thank you" },
  { fr: "s'il vous plaît", en: "please" },
  { fr: "oui", en: "yes" },
  { fr: "non", en: "no" },
  { fr: "j'habite à", en: "I live in" },
  { fr: "Je m'appelle", en: "My name is" },
  { fr: "Enchanté(e)", en: "Nice to meet you" },
  { fr: "prénom", en: "first name" },
  { fr: "nom", en: "surname / last name" },
  { fr: "Bonsoir", en: "Good evening" },
  { fr: "Comment allez-vous ?", en: "How are you? (formal)" },
  { fr: "Comment vas-tu ?", en: "How are you? (informal)" },
  { fr: "Tu vas bien?", en: "Are you doing well?" },
  { fr: "Ça va?", en: "How's it going?" },
  { fr: "Oui, je vais bien, merci", en: "Yes, I'm doing well, thank you" },
  { fr: "Bien, merci", en: "Good, thank you" },
  { fr: "Ça va, merci", en: "I'm fine, thanks" },
  { fr: "Et vous?", en: "And you? (formal)" },
  { fr: "Comment ça va?", en: "How are you doing?" },
  { fr: "Moi aussi", en: "Me too" },
  { fr: "Je suis", en: "I am" },
  { fr: "Tu t'appelles comment?", en: "What's your name? (informal)" },
  { fr: "Vous vous appelez comment?", en: "What's your name? (formal)" },
  { fr: "Vous habitez où?", en: "Where do you live? (formal)" },
  { fr: "Tu habites où?", en: "Where do you live? (informal)" },
  { fr: "où", en: "where" },
  { fr: "le", en: "the (masculine singular)" },
  { fr: "la", en: "the (feminine singular)" },
  { fr: "les", en: "the (plural)" },
  { fr: "un", en: "a / an (masculine)" },
  { fr: "une", en: "a / an (feminine)" },
  { fr: "des", en: "some (plural)" },
  { fr: "le frère", en: "the brother" },
  { fr: "la sœur", en: "the sister" },
  { fr: "le livre", en: "the book" },
  { fr: "les livres", en: "the books" },
  { fr: "la table", en: "the table" },
  { fr: "pardon", en: "excuse me" },
  { fr: "je ne comprends pas", en: "I don't understand" },
  { fr: "très bien", en: "very good" },
  { fr: "un/une", en: "one" },
  { fr: "deux", en: "two" },
  { fr: "trois", en: "three" },
  { fr: "quatre", en: "four" },
  { fr: "cinq", en: "five" },
  { fr: "six", en: "six" },
  { fr: "sept", en: "seven" },
  { fr: "huit", en: "eight" },
  { fr: "neuf", en: "nine" },
  { fr: "dix", en: "ten" },
  { fr: "manger", en: "to eat" },
  { fr: "boire", en: "to drink" },
  { fr: "parler", en: "to speak" },
  { fr: "écouter", en: "to listen" },
  { fr: "regarder", en: "to watch" },
  { fr: "lire", en: "to read" },
  { fr: "écrire", en: "to write" },
  { fr: "dormir", en: "to sleep" },
  { fr: "courir", en: "to run" },
  { fr: "marcher", en: "to walk" },
  { fr: "maison", en: "house" },
  { fr: "chat", en: "cat" },
  { fr: "chien", en: "dog" },
  { fr: "livre", en: "book" },
  { fr: "table", en: "table" },
  { fr: "chaise", en: "chair" },
  { fr: "porte", en: "door" },
  { fr: "fenêtre", en: "window" },
  { fr: "voiture", en: "car" },
  { fr: "vélo", en: "bicycle" },
  { fr: "rouge", en: "red" },
  { fr: "bleu", en: "blue" },
  { fr: "vert", en: "green" },
  { fr: "jaune", en: "yellow" },
  { fr: "noir", en: "black" },
  { fr: "blanc", en: "white" },
  { fr: "grand", en: "big" },
  { fr: "petit", en: "small" },
  { fr: "beau", en: "beautiful" },
  { fr: "laid", en: "ugly" }
];
