// Vocabulary data for FrenchMe app
const VOCAB = [
  { fr: "bonjour", en: "hello" },
  { fr: "au revoir", en: "goodbye" },
  { fr: "merci", en: "thank you" },
  { fr: "s'il vous plaît", en: "please" },
  { fr: "oui", en: "yes" },
  { fr: "non", en: "no" },
  { fr: "pardon", en: "excuse me" },
  { fr: "je ne comprends pas", en: "I don't understand" },
  { fr: "comment allez-vous?", en: "how are you?" },
  { fr: "très bien", en: "very good" },
  { fr: "un", en: "one" },
  { fr: "deux", en: "two" },
  { fr: "trois", en: "three" },
  { fr: "quatre", en: "four" },
  { fr: "cinq", en: "five" },
  { fr: "six", en: "six" },
  { fr: "sept", en: "seven" },
  { fr: "huit", en: "eight" },
  { fr: "neuf", en: "nine" },
  { fr: "dix", en: "ten" },
  { fr: "manger", en: "to eat" },
  { fr: "boire", en: "to drink" },
  { fr: "parler", en: "to speak" },
  { fr: "écouter", en: "to listen" },
  { fr: "regarder", en: "to watch" },
  { fr: "lire", en: "to read" },
  { fr: "écrire", en: "to write" },
  { fr: "dormir", en: "to sleep" },
  { fr: "courir", en: "to run" },
  { fr: "marcher", en: "to walk" },
  { fr: "maison", en: "house" },
  { fr: "chat", en: "cat" },
  { fr: "chien", en: "dog" },
  { fr: "livre", en: "book" },
  { fr: "table", en: "table" },
  { fr: "chaise", en: "chair" },
  { fr: "porte", en: "door" },
  { fr: "fenêtre", en: "window" },
  { fr: "voiture", en: "car" },
  { fr: "vélo", en: "bicycle" },
  { fr: "rouge", en: "red" },
  { fr: "bleu", en: "blue" },
  { fr: "vert", en: "green" },
  { fr: "jaune", en: "yellow" },
  { fr: "noir", en: "black" },
  { fr: "blanc", en: "white" },
  { fr: "grand", en: "big" },
  { fr: "petit", en: "small" },
  { fr: "beau", en: "beautiful" },
  { fr: "laid", en: "ugly" }
];
